### ISSUE TITLE
Fact loading (iis_version) throws exception when IIS is not available

### ISSUE THREAD

**Issue by patriksvensson** [puppetlabs/puppetlabs-powershell#121]
I noticed that fact loading for `iis_version` throws an exception if IIS is not enabled on a machine.
I traced the exception being thrown to [this line](https://github.com/puppetlabs/puppetlabs-iis/blob/master/lib/facter/iis_version.rb#L14) in the `puppetlabs-iis` repository.

The puppet run continues like normal after this, but the exception message get set as the value for the `iis_version` fact as can be seen in the image below.

![image](https://cloud.githubusercontent.com/assets/357872/16233055/48a5011a-37cd-11e6-9542-5dcad6bc51f5.png)

**Comment by jpogran** [comment]
@patriksvensson I'm assuming you opened this issue here because the puppetlabs-iis github repo has no issues tab. This is because we track bug reports and feature requests in our public JIRA tracker. If you could open an issue [here](https://tickets.puppetlabs.com/browse/MODULES) and then paste the ticket number here I'll get it added to our triage so we can investigate it.

**Comment by patriksvensson** [comment]
@Jpogran Correct. I can do that when I have access to a computer.

Do you accept pull requests for these kind of issues btw or is the source on GitHub for reference only?

**Comment by jpogran** [comment]
We do accept pull requests for most of our projects and welcome input from the community. There is always a CONTRIBUTING.md document that outlines how to do submit PRs and issues in each repo Puppet owns, however in this case puppetlabs-iis was just transitioned from a community module to a Puppet module and hasn't had the normal docs and other files added to it yet. I apologize for the oversight and will get that sorted as soon as possible.

**Comment by patriksvensson** [comment]
@jpogran I understand completely. I just wanted to see if you would accept a PR for this which you do :smile:

I've added an issue for this in your JIRA: https://tickets.puppetlabs.com/browse/MODULES-3508

**Comment by jpogran** [comment]
Thanks, I'll close this out and reply over there.
