### ISSUE TITLE
Suggestion: Have powershell errors report to a single event log event

### ISSUE THREAD

**Issue by cwb124** [puppetlabs/puppetlabs-powershell#46]
Currently, it appears that when the powershell provider runs into an error in the powershell script, it writes an event log entry for each line that would output to the screen, making reading and parsing the event log tedious.  Any way we can have it output the entire error to one event log, reducing the number of logs and making troubleshooting easier?

**Comment by joshcooper** [comment]
@cwb124 can you export the event log entries, and upload to gist or append here (if it's not too large)?

**Comment by Areson** [comment]
The split output is due to how exec handles the output from the run command. In the sync method it takes the output from the exec command and splits out each line separately and then logs that line.

**Comment by ferventcoder** [comment]
@Areson I have an issue logged where we may stop going line by line and evaluate the script as a whole.

**Comment by ferventcoder** [comment]
That would likely fix this issue. Can you follow up with a ticket in https://tickets.puppetlabs.com/browse/MODULES? If you have already created a ticket, provide the link here and let's close this.

**Comment by Areson** [comment]
I don't have a ticket yet. Are you thinking that one gets opened for the exec resource type to remove the splitting?

**Comment by glennsarti** [comment]
@Areson have you logged a ticket yet?  and yes it should be about the exec resource as you said above.

**Comment by Areson** [comment]
https://tickets.puppetlabs.com/browse/PUP-6498

**Comment by ferventcoder** [comment]
With a logged ticket, we can close this to manage the issue there. Thanks!
