### ISSUE TITLE
elseif not recognized

### ISSUE THREAD

**Issue by Tim-Co** [puppetlabs/puppetlabs-powershell#51]
I'm experiencing some weird behavior with the powershell module. I'm using version 3.7.5 on the master and agent. The agent is a Windows 2012 R2 server with powershell 4.0. I have the following template to set the A record on a Microsoft DNS server.

```powershell
$dnsserver = "<%= @dns_server %>"
$containerName = "<%= @container_name %>"
$recordName = "<%= @record_name %>"
$userName = "<%= @user_name %>"
$password = "<%= @password %>"
$TTL = '<%= @ttl %>'
$recordType = "<%= @record_type %>"

if ($recordType.ToLower() -eq "a")
    {$_recordType = "MicrosoftDNS_AType"}
elseif ($recordType.ToLower() -eq "cname")
    {$_recordType = "MicrosoftDNS_CNAMEType"}
$DNSAdmin = New-ObJect System.Management.Automation.PSCredential ($userName, (ConvertTo-SecureString $password -AsPlainText -Force))
$record = Get-WmiObject -ComputerName $dnsserver -Namespace "root\MicrosoftDNS" -Class $_recordType -Filter "ContainerName='$containerName' AND OwnerName='$recordName'" -Credential $DNSAdmin
$ipaddress = (new-object net.webclient).DownloadString('http://169.254.169.254/latest/meta-data/local-ipv4')

if ($record.IPAddress -eq $ipaddress -and $record.TTL -ne $TTL)
    {$record.Modify($TTL -as [uint32])}
elseif ($record.IPAddress -ne $ipaddress)
    {$record.Modify($record.TTL, $ipaddress)}
```

I receive the following error when the script runs...
```
Notice: /Stage[main]/Modify_dns/Exec[modifydns]/returns: elseif : The term 'elseif' is not recognized as the name of a cmdlet, function, script file, or operable program. Chec
k the spelling of the name, or if a path was included,
Notice: /Stage[main]/Modify_dns/Exec[modifydns]/returns: verify that the path is correct and try again.
Notice: /Stage[main]/Modify_dns/Exec[modifydns]/returns: At line:1 char:1
Notice: /Stage[main]/Modify_dns/Exec[modifydns]/returns: + elseif ($recordType.ToLower() -eq "cname")
Notice: /Stage[main]/Modify_dns/Exec[modifydns]/returns: + ~~~~~~
Notice: /Stage[main]/Modify_dns/Exec[modifydns]/returns:     + CategoryInfo          : ObjectNotFound: (elseif:String) [], CommandNotFoundException
Notice: /Stage[main]/Modify_dns/Exec[modifydns]/returns:     + FullyQualifiedErrorId : CommandNotFoundException
Notice: /Stage[main]/Modify_dns/Exec[modifydns]/returns:
Notice: /Stage[main]/Modify_dns/Exec[modifydns]/returns: $_recordType = "MicrosoftDNS_CNAMEType"
Notice: /Stage[main]/Modify_dns/Exec[modifydns]/returns: elseif : The term 'elseif' is not recognized as the name of a cmdlet, function, script file, or operable program. Chec
k the spelling of the name, or if a path was included,
Notice: /Stage[main]/Modify_dns/Exec[modifydns]/returns: verify that the path is correct and try again.
Notice: /Stage[main]/Modify_dns/Exec[modifydns]/returns: At line:1 char:1
Notice: /Stage[main]/Modify_dns/Exec[modifydns]/returns: + elseif ($record.IPAddress -ne $ipaddress)
Notice: /Stage[main]/Modify_dns/Exec[modifydns]/returns: + ~~~~~~
Notice: /Stage[main]/Modify_dns/Exec[modifydns]/returns:     + CategoryInfo          : ObjectNotFound: (elseif:String) [], CommandNotFoundException
Notice: /Stage[main]/Modify_dns/Exec[modifydns]/returns:     + FullyQualifiedErrorId : CommandNotFoundException
Notice: /Stage[main]/Modify_dns/Exec[modifydns]/returns:
Notice: /Stage[main]/Modify_dns/Exec[modifydns]/returns: $record.Modify($record.TTL, $ipaddress)
Notice: /Stage[main]/Modify_dns/Exec[modifydns]/returns: executed successfully
Notice: Finished catalog run in 22.56 seconds
```

The template file is in ANSI, DOS/Win line endings, and no tabs. I'm not sure what the problem may be.

**Comment by ferventcoder** [comment]
I looked this up and the only thing I've come up with is that the elseif needs to come DIRECTLY on the next line after the closing of the brace from the if statement. 

It's possible that the template may be adding spaces, but it's really troubling to see the error coming through at `line 1: char 1` - this should have happened much further down in the template.

Is this a `ps1.erb` file?

References:
 * http://stackoverflow.com/questions/26376208/powershell-2-0-conditional-else-not-recognized-as-the-name-of-a-cmdlet-func
* http://stackoverflow.com/questions/23760011/powershell-elseif-is-not-recognized

**Comment by ferventcoder** [comment]
Also please file issues in JIRA, not here.

**Comment by ferventcoder** [comment]
Would it be possible if you would set the template file to UTF-8 and try again? If that doesn't resolve it, leave it as UTF-8 and also change the line endings to Unix. Then give it another shot.

**Comment by Tim-Co** [comment]
I renamed the file to .erb and changed it to UTF-8 without BOM and it still experienced the same issue. When I changed the line endings to unix it ran with no errors but it did not make it to the second if statement, like it wasn't there. UTF-8 with BOM gave me errors about some funky characters in the script along with the errors above.

If I keep the if and elseif statements on one continuous line it works fine.

I also changed the elseif statements to multiple if statements and it works fine using ANSI, windows line endings, and .ps1 extension. The original scripts also works fine if I run it on the server manually.

**Comment by ferventcoder** [comment]
Another option is to set the closing statement on the same line as the elseif. e.g.:

```powershell
if (some condition) {
  some statements
} elseif {
```

**Comment by ferventcoder** [comment]
I think what you highlighted is a possible issue and we should follow up with a JIRA ticket.

**Comment by ferventcoder** [comment]
I filed a ticket and updated with our discussion - let's continue the conversation there https://tickets.puppetlabs.com/browse/MODULES-1996 . 

Closing this issue to continue it in JIRA.

**Comment by ferventcoder** [comment]
I've added additional questions for you over there.

**Comment by Iristyle** [comment]
As @ferventcoder alluded to, the PowerShell parser has some rules around how `if`, `else` and `elseif` are used.  Please see the following for some details of the idiosyncracies - https://unlockpowershell.wordpress.com/2012/08/21/powershell-version-3-if-else-bug/
