### ISSUE TITLE
$env:Path not refreshed from prior actions?

### ISSUE THREAD

**Issue by bdruth** [puppetlabs/puppetlabs-powershell#57]
I have a fairly simple manifest using ``chocolatey/chocolatey`` and ``puppetlabs/powershell`` - when I install a component that updates the Machine Path (i.e. ``[System.Environment]::GetEnvironmentVariable("Path","Machine")``), and subsequently issue an ``Exec`` which depends on that, it fails because Powershell doesn't see the updated Path.

I've tried setting ``path => $::path``, ``path => $([System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User"))`` and various other permutations to try to  force an up-to-date Path being used, to no avail.

Any magic to make this work? Thanks!

**Comment by ferventcoder** [comment]
I don't believe `path` can run arbitrary PowerShell, which might be why it doesn't work as you might expect.

**Comment by bdruth** [comment]
:disappointed: https://github.com/chocolatey/puppet-chocolatey/issues/63

**Comment by ferventcoder** [comment]
One thing we might do is add code to Puppet that will refresh the path values. I created https://tickets.puppetlabs.com/browse/PUP-4708 to follow up.
