### ISSUE TITLE
Cant get unless exit codes to work

### ISSUE THREAD

**Issue by tek0011** [puppetlabs/puppetlabs-powershell#72]
I am trying something like:

```
exec { 'download dsm client default':
  command =>  'Write-Host "hello"',
  path     => $::path,
  provider => powershell,
  timeout  => 500,
  logoutput => true,
  unless   => 'if ((get-item "C:/Windows/System32/notepad.exe").Name -eq "notepad.exe") { exit 0 }'
}
```

However, it does not matter what I put in to the -eq.  If I leave notepad.exe in -eq and change { exit 0} to { Write-Host "hello" }  - it indeed works.  Prints hello when -eq is "notepad.exe" and doesn't print if -eq doesnt equal "notepad.exe"

Yet, when I incorporate this in to puppet, the cmd will not get excuted, regardless of what is in the -eq.  

Any ideas whats going on here?  Ive tried forcing exit codes of 1, with else statements as well.
Can't seem to get it to work correctly.

**Comment by ferventcoder** [comment]
Apologies, can you please file this at https://tickets.puppetlabs.com/browse/MODULES?

**Comment by ferventcoder** [comment]
I believe we have seen this before - I don't recall offhand what causes it. @liamjbennett may remember

**Comment by ferventcoder** [comment]
@puppetlabs/windows anybody recall what causes this?

**Comment by tek0011** [comment]
Also the syntax above might be incorrect.  But I assure you Ive tried some 50+ ways.

```
(${(get-item "C:/Windows/System32/notepad.exe").Name -eq "derp")}) { exit 1 } else { exit 0 }
```

would likely be more correct?

either or, no go :(

**Comment by tek0011** [comment]
https://tickets.puppetlabs.com/browse/MODULES-2976

**Comment by ferventcoder** [comment]
as a workaround, if it is unless that has issues, then onlyif works

**Comment by tek0011** [comment]
I am testing that right now actually.  Let you know how it works.

**Comment by ferventcoder** [comment]
We can still close this since we have a ticket to follow up on.

**Comment by tek0011** [comment]
onlyif  gives the same broken results.

**Comment by ferventcoder** [comment]
following up on the ticket

**Comment by joshcooper** [comment]
I created a sample module that uses the powershell module awhile ago. It uses `onlyif` instead of `unless` but I believe both work as expected. I have an [init.pp](https://github.com/joshcooper/example-guest/blob/master/manifests/init.pp#L39-L44) containing:

```puppet
  exec { 'rename-guest':
    command   => template('guest/rename-guest.ps1'),
    onlyif    => template('guest/guest-exists.ps1'),
    provider  => powershell,
    logoutput => true,
  }
```

where the `onlyif` logic is in a template, so that I don't have to deal with quoting and escaping. The [guest-exists.ps1 template](https://github.com/joshcooper/example-guest/blob/master/templates/guest-exists.ps1) contains:

```powershell
if (Get-WMIObject Win32_UserAccount -Filter "Name='Guest'") { exit 0 }
else { exit 1 }
end
```

Does that work for you?

**Comment by joshcooper** [comment]
Ah, I see the comments in the ticket. Yep, need the else clause with non-zero exit.
