### ISSUE TITLE
Passing Credentials in Scripts

### ISSUE THREAD

**Issue by Areson** [puppetlabs/puppetlabs-powershell#85]
I've had a number of conversations with various Puppet folks about this and it remains a bit of a sticky issue, namely _how do we safely handle scripts where we need to pass credentials or other sensitive information to Powershell?_ 

The scenario here is that we have a situation where we need to give Powershell some credentials to perform some sort of work on the system. Due to restrictions we have to pass these credentials via Puppet in some fashion, e.g. we can't or don't have access to a key manager that Powershell can talk to directly. (I do understand there are other issues here as well, such as getting secrets securely passed in the catalog, but I'm setting that aside for now.) 

Recent incarnations of the provider, and I think the latest version if I understanding the Powershell manager code correctly, all write a temp file to disk that contains the powershell code to be invoked. This means that if I have the credentials placed directly in the script (which generally seems the route I have to take) that I'll have written them to disk. Additionally, the exec module itself has logging that will log the command out to both the event log and the Puppet report, which will expose credentials. None of these outcomes are very good.

The approach I've tried to take is going the route of signed powershell scripts so we can invoke them with command line parameters rather than using stdin or the Powershell Manager, which doesn't allow that. This seems at the moment to side-step some of the above mentioned problems depending on how you communicate those command line parameters to the provider. However, I'd like to align with the longer-term strategy, if possible, of how Powershell scripts are invoked within the Puppet supported provider.

So...what's the best way of handling this?

**Comment by ferventcoder** [comment]
Unfortunately a GitHub issue is not the best place for this conversation. Might I suggest you write this up in a ticket and then ask on the puppet-dev at google groups email list?

**Comment by ferventcoder** [comment]
> Recent incarnations of the provider, and I think the latest version if I understanding the Powershell manager code correctly, all write a temp file to disk that contains the powershell code to be invoked. This means that if I have the credentials placed directly in the script (which generally seems the route I have to take) that I'll have written them to disk. Additionally, the exec module itself has logging that will log the command out to both the event log and the Puppet report, which will expose credentials. None of these outcomes are very good.


The PowerShell manager code writes nothing to disk that I'm aware of - @jpogran  for verification.

**Comment by ferventcoder** [comment]
> Additionally, the exec module itself has logging that will log the command out to both the event log and the Puppet report, which will expose credentials. 

IIRC there is a way to not log output.

**Comment by ferventcoder** [comment]
> Recent incarnations of the provider, and I think the latest version if I understanding the Powershell manager code correctly, all write a temp file to disk that contains the powershell code to be invoked. This means that if I have the credentials placed directly in the script (which generally seems the route I have to take) that I'll have written them to disk. 

Additional information here - when the 1.x PowerShell provider writes this file to disk, it holds an exclusive lock on the file and it deletes it immediately after use.

**Comment by ferventcoder** [comment]
> The approach I've tried to take is going the route of signed powershell scripts so we can invoke them with command line parameters rather than using stdin or the Powershell Manager, which doesn't allow that. 

Authenticode signed PowerShell scripts not working is news to me. I've signed the Chocolatey provider's install script and it is running in the 1.x PowerShell provider just fine. 


FWIW, the PowerShell manager code is part of the 2.x provider and it is unreleased at this time, and possibly subject to bugs. If you are finding one, please report it as a ticket at https://tickets.puppet.com/browse/MODULES. Thanks!

**Comment by Areson** [comment]
> The PowerShell manager code writes nothing to disk that I'm aware of

Confirmed. I mistook the loading of the template from file as a possible temp file write.

> IIRC there is a way to not log output.

True, but having debugging on can still log I believe.

> Additional information here - when the 1.x PowerShell provider writes this file to disk, it holds an exclusive lock on the file and it deletes it immediately after use.

Yup! Not a problem per se, but writing any credentials to disk is something I'd like to avoid.

> Authenticode signed PowerShell scripts not working is news to me. I've signed the Chocolatey provider's install script and it is running in the 1.x PowerShell provider just fine.

It works just fine. It's more that the current provider doesn't let you leverage them fully. If the script is signed then the exclusive lock isn't really necessary, as tampering with the script would cause it to fail. If the exclusive lock is released then the script can be called with the "-file" parameter and additional parameters can be passed to the script.

**Comment by ferventcoder** [comment]
> It works just fine. 

😓  whew!

> It's more that the current provider doesn't let you leverage them fully.

True.

**Comment by ferventcoder** [comment]
> True, but having debugging on can still log I believe.

Yup, which is more of an issue with Puppet exec itself rather than this provider. But definitely something to consider. 

Secrets are definitely a harder concept on Windows - have you looked at black box? https://github.com/StackExchange/blackbox

I'm not recommending it, as I haven't used it, but I know StackExchange does and it's a tool to be aware of because it works on Windows unlike some of the other Puppet secrets providers.

**NOTE:** While these things certainly limit the visibility of the secret, if you are passing it through to PowerShell, at some point that value may be able to be seen. One thing I do is to limit what I log and use variables attached to environment values, which you can pass through to the exec.

**Comment by Areson** [comment]
Started a thread over on the Puppet-Dev group:
https://groups.google.com/forum/#!topic/puppet-dev/YnKDaJcQrNs

**Comment by Areson** [comment]
Closing due to no longer being an issue since the 2.0.0 provider was released.

**Comment by ferventcoder** [comment]
Related to https://github.com/puppetlabs/puppetlabs-powershell/issues/48
